# .cirrus.yml
# Cirrus CI configuration for building a custom Android kernel.

kernel_build_task:
  container:
    image: ubuntu:20.04
    cpu: 8
    memory: 16G

  ndk_cache:
    folder: build_tools/android-ndk-r27c # Or your NDK version
    fingerprint_script: echo "ndk-r27c-cache-key-v1"

  gcc_cache:
    folder: build_tools/aarch64 # <-- UPDATED to match GCC_AARCH64_TARGET_DIR_NAME
    fingerprint_script: echo "gcc-4.9-lineageos-github-clone-aarch64dir-v1" # <-- NEW FINGERPRINT

  env:
    DEBIAN_FRONTEND: noninteractive

  apt_get_script: # Install necessary dependencies
    - apt-get update -y
    - apt-get install -y --no-install-recommends \
        build-essential \
        bc \
        bison \
        ca-certificates \
        curl \
        device-tree-compiler \
        flex \
        git \
        gperf \
        libarchive-tools \
        libfl-dev \
        liblz4-tool \
        libssl-dev \
        lz4 \
        make \
        python3 \
        software-properties-common \
        unzip \
        wget \
        zip \
        zlib1g-dev

  build_script:
    - chmod +x build_kernel.sh
    - ./build_kernel.sh

  artifacts:
    path: "larry-KSUN-SuSFS-*-*.zip" # Glob pattern for the final zip
    type: application/zip
